fix(llmobs): openai_agents check for current_span (#15645)
## Description

span._set_ctx_item(AGENT_MANIFEST, manifest)
  AttributeError: 'NoneType' object has no attribute '_set_ctx_item'
The ddtrace code assumes current_span is always present, but it's None
in some cases

A co-worker was getting an error
https://dd.slack.com/archives/CCL9CU9FB/p1765817718098209

## Testing

<!-- Describe your testing strategy or note what tests are included -->

## Risks

<!-- Note any risks associated with this change, or "None" if no risks
-->

## Additional Notes

<!-- Any other information that would be helpful for reviewers -->